Repository ITISFoundation/osparc-simcore-clients, pull requests merged in 2023-07, with the labels that each got.

#47 ♻️ Fix import and docu
  .github/workflows/build-n-publish.yml
  .github/workflows/publish-python-client.yml
  clients/python/README.md
  clients/python/client/osparc/__init__.py
  clients/python/client/osparc/_info.py
  clients/python/client/osparc/_warnings_and_errors.py
  clients/python/client/osparc/api.py
  clients/python/client/osparc/info/__init__.py
  clients/python/client/osparc/models.py
  clients/python/docs/BasicTutorial.ipynb
  clients/python/docs/BasicTutorial.md
  clients/python/docs/README.md
  clients/python/docs/info.md
  clients/python/test_osparc/test_basic.py
  clients/python/test_osparc_client/test_body_upload_file_v0_files_content_put.py
  clients/python/test_osparc_client/test_file.py
  clients/python/test_osparc_client/test_files_api.py
  clients/python/test_osparc_client/test_groups.py
  clients/python/test_osparc_client/test_http_validation_error.py
  clients/python/test_osparc_client/test_job.py
  clients/python/test_osparc_client/test_job_inputs.py
  clients/python/test_osparc_client/test_job_outputs.py
  clients/python/test_osparc_client/test_job_status.py
  clients/python/test_osparc_client/test_meta.py
  clients/python/test_osparc_client/test_meta_api.py
  clients/python/test_osparc_client/test_profile.py
  clients/python/test_osparc_client/test_profile_update.py
  clients/python/test_osparc_client/test_solver.py
  clients/python/test_osparc_client/test_solvers_api.py
  clients/python/test_osparc_client/test_task_states.py
  clients/python/test_osparc_client/test_user_role_enum.py
  clients/python/test_osparc_client/test_users_api.py
  clients/python/test_osparc_client/test_users_group.py
  clients/python/test_osparc_client/test_validation_error.py
Labels: refactoring

#49 🔨 🧪 Add notebook tests
  .github/workflows/publish-python-client.yml
  clients/python/Makefile
  clients/python/README.md
  clients/python/client/osparc/__init__.py
  clients/python/client/osparc/_warnings_and_errors.py
  clients/python/client/osparc/api.py
  clients/python/client/osparc/models.py
  clients/python/docs/BasicTutorial.ipynb
  clients/python/requirements/test.txt
  clients/python/test/e2e/data/config_test.ipynb
  clients/python/test/e2e/test_notebooks.py
  clients/python/test/test_osparc/__init__.py
  clients/python/test/test_osparc/test_basic.py
  clients/python/test/test_osparc/test_osparc_client/__init__.py
  clients/python/test/test_osparc/test_osparc_client/test_body_upload_file_v0_files_content_put.py
  clients/python/test/test_osparc/test_osparc_client/test_file.py
  clients/python/test/test_osparc/test_osparc_client/test_files_api.py
  clients/python/test/test_osparc/test_osparc_client/test_groups.py
  clients/python/test/test_osparc/test_osparc_client/test_http_validation_error.py
  clients/python/test/test_osparc/test_osparc_client/test_job.py
  clients/python/test/test_osparc/test_osparc_client/test_job_inputs.py
  clients/python/test/test_osparc/test_osparc_client/test_job_outputs.py
  clients/python/test/test_osparc/test_osparc_client/test_job_status.py
  clients/python/test/test_osparc/test_osparc_client/test_meta.py
  clients/python/test/test_osparc/test_osparc_client/test_meta_api.py
  clients/python/test/test_osparc/test_osparc_client/test_profile.py
  clients/python/test/test_osparc/test_osparc_client/test_profile_update.py
  clients/python/test/test_osparc/test_osparc_client/test_solver.py
  clients/python/test/test_osparc/test_osparc_client/test_solvers_api.py
  clients/python/test/test_osparc/test_osparc_client/test_task_states.py
  clients/python/test/test_osparc/test_osparc_client/test_user_role_enum.py
  clients/python/test/test_osparc/test_osparc_client/test_users_api.py
  clients/python/test/test_osparc/test_osparc_client/test_users_group.py
  clients/python/test/test_osparc/test_osparc_client/test_validation_error.py
  clients/python/test_osparc_client/test_groups.py
  clients/python/test_osparc_client/test_job.py
  clients/python/test_osparc_client/test_job_status.py
  clients/python/test_osparc_client/test_profile.py
  docker/osparc_python_tutorial_testing/Dockerfile
  docker/osparc_python_tutorial_testing/build-n-publish.bash
  scripts/gh.bash
  scripts/install_ci_osparc_python_client.bash
Labels: maintenance

#51 📝 Support versioning on website
  .github/workflows/github-pages.yml
  Makefile
  README.md
  clients/python/Makefile
  clients/python/docs/BasicTutorial.md
  clients/python/docs/README.md
  clients/python/docs/v0.5.0/README.md
  clients/python/requirements/dev.txt
  clients/python/requirements/doc.txt
  docs/doc_entrypoint.md
  docs/navbar.md
  index.html
Labels: documentation

#52 🐛 Update README.md
  README.md
Labels: documentation

#54 🧪Exted e2e testing
  .github/CODEOWNERS
  .gitignore
  .openapi-generator/VERSION
  .pre-commit-config.yaml
  clients/python/Makefile
  clients/python/client/osparc/__init__.py
  clients/python/client/osparc/api.py
  clients/python/client/osparc/models.py
  clients/python/client/setup.py
  clients/python/requirements/test.txt
  clients/python/test/e2e/ci/_utils.py
  clients/python/test/e2e/ci/check_for_failures.py
  clients/python/test/e2e/ci/compatible_client_server.py
  clients/python/test/e2e/ci/generate_html_table.py
  clients/python/test/e2e/ci/generate_pyproject_toml.py
  clients/python/test/e2e/ci/install_osparc_python_client.bash
  clients/python/test/e2e/ci/install_osparc_python_client.py
  clients/python/test/e2e/ci/postprocess_e2e.py
  clients/python/test/e2e/ci/preprocess_client_config.bash
  clients/python/test/e2e/ci/run_e2e_python_tests.bash
  clients/python/test/e2e/data/server_client_compatibility.json
  clients/python/test/e2e/test_notebooks.py
  clients/python/test/test_osparc/test_osparc_client/test_body_upload_file_v0_files_content_put.py
  clients/python/test/test_osparc/test_osparc_client/test_file.py
  clients/python/test/test_osparc/test_osparc_client/test_groups.py
  clients/python/test/test_osparc/test_osparc_client/test_http_validation_error.py
  clients/python/test/test_osparc/test_osparc_client/test_job.py
  clients/python/test/test_osparc/test_osparc_client/test_job_inputs.py
  clients/python/test/test_osparc/test_osparc_client/test_job_outputs.py
  clients/python/test/test_osparc/test_osparc_client/test_job_status.py
  clients/python/test/test_osparc/test_osparc_client/test_meta.py
  clients/python/test/test_osparc/test_osparc_client/test_profile.py
  clients/python/test/test_osparc/test_osparc_client/test_profile_update.py
  clients/python/test/test_osparc/test_osparc_client/test_solver.py
  clients/python/test/test_osparc/test_osparc_client/test_task_states.py
  clients/python/test/test_osparc/test_osparc_client/test_user_role_enum.py
  clients/python/test/test_osparc/test_osparc_client/test_users_group.py
  clients/python/test/test_osparc/test_osparc_client/test_validation_error.py
  docker/osparc_python_tutorial_testing/Dockerfile
  docker/osparc_python_tutorial_testing/build-n-publish.bash
  scripts/common.Makefile
  scripts/install_ci_osparc_python_client.bash
  scripts/jq.bash
Labels: maintenance

#57 🐛 add jinja2 import to generate html table
  clients/python/requirements/test.txt
Labels: maintenance

#59 ✨ Increment api version
  .pre-commit-config.yaml
  api/config.json
  api/openapi.json
  clients/python/Makefile
  clients/python/client/osparc/__init__.py
  clients/python/client/osparc/api.py
  clients/python/client/osparc/models.py
  clients/python/test/test_osparc/test_osparc_client/test_meta.py
Labels: enhancement
