Repository ITISFoundation/osparc-simcore-clients, pull requests merged in 2023-10, with the labels that each got.

#73 🐛 🧪 Fix e2e client tests
  clients/python/test/e2e/ci/check_for_failures.py
  clients/python/test/e2e/ci/generate_html_table.py
  clients/python/test/e2e/ci/postprocess_e2e.py
  clients/python/test/e2e/test_files_api.py
Labels: bug

#77 📝 Expanding doc to easier find doc for api versions
  .github/workflows/publish-python-client.yml
  README.md
  docs/doc_entrypoint.md
  index.html
Labels: documentation

#78 📝 Update PULL_REQUEST_TEMPLATE.md with instructions for internal devs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#79 🔨 setup workflow file for publishing to pypi
  .github/workflows/publish-python-client.yml
Labels: maintenance

#80 🐛 Fix dependency issue
  api/config.json
  clients/python/Makefile
  clients/python/client/setup.py
Labels: maintenance

#82 🐛 🧪 Ensure correct depencies
  clients/python/client/setup.py
  clients/python/requirements/test.txt
  clients/python/test/test_osparc/test_basic.py
Labels: bug, add test
