Repository ITISFoundation/osparc-simcore-clients, pull requests merged in 2024-06, with the labels that each got.

#157 🗑️ Deprecate old python versions
  README.md
  clients/python/client/osparc/__init__.py
  clients/python/client/osparc/models.py
  clients/python/client/setup.py
  clients/python/requirements/e2e-test.txt
  docs/_media/code_lifecycle.png
Labels: maintenance

#156 ✨🗑️ ⬆️ Propagate server-side changes to client
  .github/workflows/build-python-client.yml
  .github/workflows/publish-python-client.yml
  api/openapi.json
  clients/python/client/osparc/_files_api.py
  clients/python/client/osparc/_models.py
  clients/python/client/osparc/_solvers_api.py
  clients/python/client/osparc/_studies_api.py
  clients/python/client/osparc/models.py
  clients/python/client/setup.py
  clients/python/requirements/unit-test.txt
  clients/python/test/test_osparc/conftest.py
  clients/python/test/test_osparc/test_apis.py
  clients/python/test/test_osparc/test_basic.py
Labels: enhancement, add test

#158 🐛 Minor fixes
  README.md
  clients/python/client/osparc/_solvers_api.py
  clients/python/client/osparc/_studies_api.py
Labels: bug

#162 ♻️ Enhances e2e testing
  clients/python/client/osparc/__init__.py
  clients/python/test/conftest.py
  clients/python/test/e2e/ci/e2e/e2e/_models.py
  clients/python/test/e2e/ci/e2e/e2e/postprocess.py
  clients/python/test/e2e/conftest.py
  clients/python/test/e2e/test_notebooks.py
  clients/python/test/pytest.ini
  clients/python/test/test_osparc/conftest.py
  clients/python/test/test_osparc/test_apis.py
Labels: enhancement

#163 ✨ Add download-study-logs-fcn
  api/openapi.json
  clients/python/client/osparc/_files_api.py
  clients/python/client/osparc/_http_client.py
  clients/python/client/osparc/_solvers_api.py
  clients/python/client/osparc/_studies_api.py
  clients/python/client/osparc/_utils.py
  clients/python/test/e2e/conftest.py
  clients/python/test/e2e/test_files_api.py
  clients/python/test/e2e/test_notebooks.py
  clients/python/test/e2e/test_solvers_api.py
  clients/python/test/e2e/test_studies.py
Labels: enhancement, add test
