Repository ITISFoundation/osparc-simcore-clients, pull requests merged in 2024-10, with the labels that each got.

#187 📝 Enhances doc and fixes missing links
  clients/python/docs/BasicTutorial_v0.5.0.md
  clients/python/docs/BasicTutorial_v0.6.0.md
  clients/python/src/osparc/_api_client.py
  docs/doc_entrypoint.md
Labels: bug, documentation

#188 🐛📝 Fixes and tests links on the doc
  clients/python/test/tests_docs.py
  docs/doc_entrypoint.md
Labels: documentation

#190 📝 doc: new references to external resources
  docs/doc_entrypoint.md
Labels: documentation

#189 ✨ Client for public api v0.7
  .gitignore
  .vscode/settings.template.json
  Makefile
  README.md
  VERSIONING.md
  api/.gitignore
  api/Makefile
  api/openapi.json
  clients/python/Makefile
  clients/python/README.md
  clients/python/pyproject.toml
  clients/python/setup.py
  clients/python/src/osparc/__init__.py
  clients/python/src/osparc/_api_client.py
  clients/python/src/osparc/_api_files_api.py
  clients/python/src/osparc/_api_solvers_api.py
  clients/python/src/osparc/_api_studies_api.py
  clients/python/src/osparc/_exceptions.py
  clients/python/src/osparc/_settings.py
  clients/python/src/osparc/_utils.py
  clients/python/src/osparc/_version.py
  clients/python/src/osparc/api.py
  clients/python/src/osparc/exceptions.py
  clients/python/src/osparc/models.py
  clients/python/test/e2e/conftest.py
  docs/doc_entrypoint.md
  requirements.txt
  scripts/common.Makefile
  scripts/compute_version.bash
Labels: documentation, enhancement

#195 🐛 fix publish workflow
  clients/python/Makefile
Labels: bug

#197 ♻️ Fix e2e to use pypi
  .pre-commit-config.yaml
  clients/python/Makefile
  clients/python/test/e2e/ci/bash/install_osparc_python_client.bash
  clients/python/test/e2e/ci/bash/osparc_version.bash
Labels: bug

#198 🐛 Fix prerelease installation
  clients/python/Makefile
Labels: bug

#200 📝 Enhance documentation
  .github/workflows/github-pages.yml
  clients/python/docs/BasicTutorial_v0.5.0.md
  clients/python/docs/BasicTutorial_v0.6.0.md
  clients/python/docs/BasicTutorial_v0.8.0.ipynb
  clients/python/docs/WalletTutorial_v0.8.0.ipynb
  clients/python/docs/v0.5.0/README.md
  clients/python/docs/v0.6.0/README.md
  clients/python/docs/v0.8.0/README.md
  clients/python/test/e2e/test_notebooks.py
  docs/doc_entrypoint.md
  docs/navbar.md
Labels: documentation, add test
